geccoplus profiles
BIH-CEI/napkon-geccoplus pull request #4
Opened 2021-12-07 15:14 UTC by glichtner

2021-12-15 12:24 UTC, ylboerner requested changes
Great PR! There is only one required change, one annotation and two suggestions. We are definitely on track to finish these profiles by the end of the week.

2021-12-15 12:24 UTC, ylboerner commented on input/fsh/geccoplus/p-allergies.fsh
> +Profile: Allergies
Great job! Just so that you are aware: In order for allergies to be actionable for decision support, using Condition alone is not sufficient as the allergy or intolerance condition needs to be represented as an AllergyIntolerance. So in case the data will be used for decision support, we should add an allergyintolerance profile as well. If not, a condition alone is fine.

2021-12-15 12:24 UTC, ylboerner commented on input/fsh/geccoplus/p-highest-school-degree.fsh
> +  * coding[loinc] = $loinc#63504-5 "What is the highest grade or level of school you have completed or the highest degree you have received [NHANES]"
As this is an observation and not a questionnaire, I would opt for this code: https://loinc.org/82589-3/

2021-12-15 12:24 UTC, ylboerner commented on input/fsh/geccoplus/p-symptoms.fsh
> +Profile: Symptoms
We should discuss this profile in a bit more detail and decide whether we might need to split this up into an observation and condition profile. These are the guidelines from the specification:

Use the Observation resource when a symptom is resolved without long term management, tracking, or when a symptom contributes to the establishment of a condition.

Use Condition when a symptom requires long term management, tracking, or is used as a proxy for a diagnosis or problem that is not yet determined.

For most of the codes in the referenced bound valuesets, Condition is applicable but for light symptoms such as dizziness and nasal discharge, we might want to use Observation.

2021-12-15 12:24 UTC, ylboerner commented on input/fsh/geccoplus/p-urine-diagnostics.fsh
> +* valueCodeableConcept from PositiveNegative (required)
In case you would like to stay consistent with the rest of the profiles, we should use valueBoolean here as that was the preferred solution in cardiology and pediatrics I believe.

2021-12-17 09:50 UTC, glichtner commented on input/fsh/geccoplus/p-highest-school-degree.fsh
> +  * coding[loinc] = $loinc#63504-5 "What is the highest grade or level of school you have completed or the highest degree you have received [NHANES]"
agreed & changed

2021-12-17 10:02 UTC, glichtner commented on input/fsh/geccoplus/p-urine-diagnostics.fsh
> +* valueCodeableConcept from PositiveNegative (required)
we discussed this internally and decided to leave it with valueCodeableConcept and SNOMED CT codes

2021-12-17 11:13 UTC, glichtner commented on input/fsh/geccoplus/p-allergies.fsh
> +Profile: Allergies
after discussion, we decided to use only Condition, as there is currently no use case known to us that should use GECCO/GECCOplus for clinical decision support

2021-12-17 11:13 UTC, ylboerner approved these changes

2021-12-17 11:13 UTC, glichtner commented on input/fsh/geccoplus/p-symptoms.fsh
> +Profile: Symptoms
As all parameters in GECCOplus are recorded in the context of COVID-19 patients, we have decided to leave all repsonse options as Condition

2021-12-17 11:14 UTC, merged